export const UpdateType = {
  NONE: `NONE`,
  PATCH: `PATCH`,
  MINOR: `MINOR`,
  MAJOR: `MAJOR`,
  INIT: `INIT`
};

export const UserAction = {
  UPDATE_PICTURE: `UPDATE_PICTURE`,
  UPDATE_USER_FAVORITE: `UPDATE_USER_FAVORITE`,
  UPDATE_USER_LIKE: `UPDATE_USER_LIKE`,
  ADD_PICTURE: `ADD_PICTURE`,
  ADD_COMMENT: `ADD_COMMENT`,
  DELETE_PICTURE: `DELETE_PICTURE`,
  DELETE_COMMENT: `DELETE_COMMENT`,
};
