export const UpdateType = {
  NONE: `NONE`,
  PATCH: `PATCH`,
  MINOR: `MINOR`,
  MAJOR: `MAJOR`,
  INIT: `INIT`
};

export const UserAction = {
  UPDATE_PICTURE: `UPDATE_PICTURE`,
  UPDATE_USER_FAVORITE: `UPDATE_USER_FAVORITE`,
  UPDATE_USER_LIKE: `UPDATE_USER_LIKE`,
  UPDATE_COMMENT: `UPDATE_COMMENT`,
  LOAD_PICTURE: `LOAD_PICTURE`,
  ADD_COMMENT: `ADD_COMMENT`,
  DELETE_PICTURE: `DELETE_PICTURE`,
  DELETE_COMMENT: `DELETE_COMMENT`,
};

export const MenuItem = {
  LOAD_PICTURE: `LOAD_PICTURE`,
  PROFILE: `PROFILE`,
  SING_OUT: `SING_OUT`,
}
